package be.famifed.dibiss.enums;
public enum AcquisitionScale {
	REGULAR_SCALE, //S 40
	RAISED_SCALE_UNEMPLOYED_RETIRED,//S 42 Bis
	RAISED_ORPHAN_SUPPLEMENT, //S 50 Bis
	RAISED_SUPPLEMENT_DISABLED_EMPLOYEE, //S 50 Ter
	SCALE_BILATERAL_ALGERIA, 
	SPECIAL_SCALE_BILATERAL_MOROCCO_TURKEY_TUNESIA, 
	SPECIAL_SCALE_BILATERAL_ABOVEGROUND_MINERS, 
	SPECIAL_SCALE_BILATERAL_FORMER_YUGOSLAVIA_KOSOVO, 
	SCALE_INDEPENDENT //S 17 G
	
}