package be.famifed.dibiss.enums;
public enum BondType {
    PARENT,
    STEP_PARENT,
    ADOPTANT,
    CUSTODIAN,
    GRAND_PARENT,
    UNCLE_AUNT,
    PARTNER_GRAND_PARENT,
    PARTNER_UNCLE_AUNT,
    SIBLING,
    PARTNER_PARENT_ADOPTANT,
    PARTNER_CUSTODIAN,
    EX_STEP_PARENT_OR_EX_PARTNER_ADOPTANT,
    EX_PARTNER_CUSTODIAN,
    PLACEMENT,
    OTHER,
    NONE
}