package be.famifed.dibiss.enums;
public enum Ground {
	
	CHILD_YOUNGER_THAN_18,
	STUDENT_18_OR_OLDER,
	APPRENTICESHIP,
	WAITINGPERIOD_UNEMPLOYEMENT_SETTLEMENT,
	PREPARED_ESSAY_END_OF_STUDIES,
	CHILD_BORN_BEFORE_FIRST_JULY_1966_HANDICAPPED,
	CHILD_BORN_AFTER_30TH_JUNE_1966_HANDICAPPED,
    PART_TIME_EDUCATION,
    COMPANY_TRAINING,
	NONE
	
}