package be.famifed.dibiss.enums;
public enum WorkerStatus {
    STATUTORY_EMPLOYED, CONTRACTUAL_EMPLOYED, DISABLED, RETIRED, ORPHAN, ENTITLED_TO_A_SURVIVAL_PENSION, DETAINEE, MINISTER, SELF_EMPLOYED, OTHER
}